### ISSUE TITLE
Allow Projects to be defined via .asf.yaml

### ISSUE THREAD

**Issue by dave2wave** [apache/tooling-trusted-releases#139]
One way that we could improve the UX around defining projects is to add a section to the `.asf.yaml` process which would allow one or more projects that are sourced in one of a PMC's repositories.

This could look something like:

```
projects:
  - name: project1
     id: ...
     folder: ...
     description: ...
     keys: ...
     tags: ...
     doap: (url or generate)
  - name: project2
     ...
```

The .asf.yaml processing could then use an ATR api to create/update the project and generate (or use) the DOAP. This ATR api could also update `projects.apache.org`'s `projects.xml`.
